name: qbic-pipelines/querynator release API docs
on:
  - pull_request
  - push

# Cancel if a newer run is started
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  Prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install prettier
        run: npm install -g prettier
      - name: Run Prettier
        run: prettier --check ${GITHUB_WORKSPACE}
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install python dependencies
        run: |
          pip install --upgrade pip
          pip install -r docs/requirements.txt
          pip install .

      - name: Build HTML docs
        run: make -C docs html
